- name: add Redis PPA
  sudo: true
  apt_repository: repo=ppa:chris-lea/redis-server

- name: install 'redis-server'
  sudo: true
  apt: pkg=redis-server state=latest
  register: result

- name: create redis data dir
  sudo: true
  file: >
    path={{ redis.dir }}
    state=directory
    owner=redis
    group=redis

- name: generate config file
  sudo: true
  template: >
    src=redis.conf.j2
    dest=/etc/redis/redis.conf
    owner=root
    group=root
    mode=0644
  notify: restart redis
